### PR TITLE
remove caching and updated depedencies to match current go version

### PR DESCRIPTION
**Pull request by HT808s**
Hi,
I made modifications to match current golang version
I also made some slight changes with the workflow and added glide to support dependency management

### CODE REVIEW

**Comment by sklarsa** [comment]
App builds for me when running `go build .` We should add an issue to update the Makefile since it doesn't work anymore.

**Comment by HT808s** [comment]
@sklarsa You're right about the Makefile !
I'll have a look at it

**Comment by HT808s** [comment]
@sklarsa I made a new Makefile
You can check it out !

**Comment by sklarsa** [comment]
Works for me!  Only additional suggestion I have is to include `github.com/fatih/color` and `golang.org/x/net/html` in the ./vendor folder (I've only used govendor so far).

I'm going to take a look at adding additional data sources (like Quandl) and also adding some general portfolio analytics for index investing since that's my strategy at the moment.  Thanks for keeping this thing alive!  I think it can be pretty useful since I'm running into limitations using a google sheet and the built-in googlefinance api

**Comment by HT808s** [comment]
For the dependencies I used [glide](https://github.com/Masterminds/glide) which is able to handle vendor dependencies
Here are the two files describing the dependencies [glide.lock](https://github.com/HT808s/gofinance/blob/b901f83f997f3efbb17d03a781f2745914774fd0/glide.lock) and [glide.yaml](https://github.com/HT808s/gofinance/blob/b901f83f997f3efbb17d03a781f2745914774fd0/glide.yaml)

I'm happy you are thinking about contributing to the project
I've planned to do some serious refactoring in order to ease further contributions !
Then I will start to write tests and then put it into a continuous integration system like maybe [drone.io](https://github.com/drone/drone)

**Pull request merged**
